### ISSUE TITLE
Safety>Accessories

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/Kookaberry-Reference-Guide#1]
Safety>Accessories. Reading this it might appear that accessories needing more than 3.3v and drawing more than 100 milliamps cannot be used with the the Kookaberry.

I recognise that what you are addressing is the ability of the K to directly power accessoris, but this might be made clearer

**Comment by TDStrasser** [comment]
Thanks John. I have addressed the issue in an update to be published shortly.  The prohibition is on any voltage exceeding 3.3V on signal pins and any other connector except the power input connectors (5V USB and up to 12V battery).  Accessories requiring higher power supply voltages will need suitable adapters.  They must still not, however, present signal voltage in excess of 3.3V, which will damage the Kookaberry computer chip.
