### ISSUE TITLE
KookaSpecific Title

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/Kookaberry-Reference-Guide#6]
Currently the heading Kooka Specific Module Library is under Kooka Software and should be in a sparate section - as per the menu

**Comment by TDStrasser** [comment]
There are two modules (kooka and machine) under this heading.  Both are Kookaberry Software in that they are modules provided with and specific to the Kookaberry. The menue is constructed from the text files and their hierarchy. I don't see the issue.

**Comment by TDStrasser** [comment]
Thanks for your email clarification.  There was a preamble before the machine.Pin class that didn't have a heading. This has been added.
