### ISSUE TITLE
LSM303 Accelerometer

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/Kookaberry-Reference-Guide#9]
The Kooka Firmware support both the LSM303C ( no obsolete) and the LSM303AGR.  Mechanically they fit the same pcb pattern.  The register allocation in the ICs are different and hence there are two divers in the Kooka Firmware

**Comment by TDStrasser** [comment]
The drivers are named the same albeit different chips on STM32 and RP2040.
Text changed to LSM303C/AGR where appropriate.
